---
title: "04-Export"
author: "C A Pellett"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

```{r}
load("../data/pop_proj.rda")

```

```{r}
unique(pop_proj$Period)
unique(pop_proj$Scenario)
unique(pop_proj$Type)
unique(pop_proj$Type2)
unique(pop_proj$County)

pop_proj |>
  dplyr::filter(Period == 'Original' & Edition == '2022' & County == 'SOUTH CAROLINA' & 
                  Type2 %in% c('Estimate', '2022 RFA Projection')) |>
  dplyr::select(Year, Population) |>
  write.csv(file='RFA 2022 Vintage Statewide Population Projections.csv')
  

```


```{r}
unique(pop_proj$Edition)

pop_proj_x <- pop_proj %>%
  dplyr::filter(Edition == '2022')

unique(pop_proj_x$Scenario)
unique(pop_proj_x$Type)
unique(pop_proj_x$Type2)

unique(pop_proj_x$Period)

pop_proj_x %>%
  dplyr::filter(Scenario == 'Estimate') %>%
  dplyr::select(County, Year, Population) %>%
  tidyr::pivot_wider(names_from=Year, values_from=Population) %>%
  readr::write_excel_csv('export//Population_historic.csv')

pop_proj_x %>%
  dplyr::filter(Scenario == 'Moderate') %>%
  dplyr::select(County, Year, Population) %>%
  tidyr::pivot_wider(names_from=Year, values_from=Population) %>%
  readr::write_excel_csv('export//Population_moderate.csv')

pop_proj_x %>%
  dplyr::filter(Scenario == 'High') %>%
  dplyr::select(County, Year, Population) %>%
  tidyr::pivot_wider(names_from=Year, values_from=Population) %>%
  readr::write_excel_csv('export//Population_high.csv')

```
