---
title: "Laljeet Sangha"
output: html_document
date: "2024-03-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
counties <- list(
  c("Allendale"),
  c("Colleton"),
  c("Hampton", "Jasper"),
  c("Jasper", "Hampton"),
  c("Allendale", "Hampton"),
  c("Bamberg"),
  c("Hampton"),
  c("Barnwell"),
  c("Beaufort"),
  c("Beaufort", "Hampton"),
  c("Orangeburg"),
  c("Aiken"),
  c("Jasper"),
  c("Edgefield"),
  c("Colleton", "Bamberg"),
  c("Barnwell", "Aiken"),
  c("Charleston"),
  c("Chesterfield", "Kershaw", "Lancaster"),
  c("Beaufort", "Jasper"),
  c("Bamberg", "Barnwell")
)

# Flatten the list of lists into a single vector
all_counties <- unlist(counties)

# Find the unique counties
unique_counties <- unique(all_counties)

getwd()

load("./data/pop_proj.rda")

```


```{r}
filtered_data <- pop_proj %>%
  dplyr::mutate(County = stringr::str_to_title(County)) %>%
  dplyr::filter(County %in% unique_counties) |> 
  dplyr::filter(Edition == 2022)

```




```{r}
library(ggplot2)
library(RColorBrewer)
color_palette <- brewer.pal(n = 3, name = "Set2")  # Color blind friendly 

population_plot <- ggplot(filtered_data, aes(x = Year, y = Population / 1000, group = Scenario, color = Scenario)) +
  geom_line(linewidth = 1) + 
 scale_color_manual(values = setNames(color_palette, c("Moderate", "High", "Estimate"))) +
  theme_bw(base_size = 14) +  
  # facet_wrap(~ County,  ncol = 5) +
   facet_wrap(~ County, scales = 'free_y', ncol = 5) +
  labs(y = "Population (thousands)", x = "Year") +  
  theme(
    legend.position = 'bottom',
    legend.title = element_blank(),
    legend.text = element_text(size = 12),  
    strip.text = element_text(size = 14, face = "bold"),  
    axis.title = element_text(size = 14),  
    axis.text.x = element_text(angle = 45, hjust = 1, size = 12),  
    axis.text.y = element_text(size = 12),  
    plot.title = element_text(size = 16, face = "bold"), 
    plot.subtitle = element_text(size = 14)  
  )+
  theme_bw()


# population_plot <- population_plot + labs(title = "Projected Population Growth", subtitle = "2022-2070")


print(population_plot)


ggsave(filename = "./git_ignore/plots/population_plot.png", plot = population_plot, width = 8, height = 4, units = "in", dpi = 600)

# ggsave(filename = "./git_ignore/plots/population_plot_fixy.png", plot = population_plot, width = 8, height = 4, units = "in", dpi = 600)
```

see the counties and select few for presentation
```{r}
select_counties <- c("Charleston","")

```

