---
title: "Population Projection Methodology"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Population Projection Methodology}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette describes the methodology used to produce the SC population projections. Complete metadata from SC RFA is provided for both the 2019 and 2022 editions. Then, the methods for extending the projections to 2070 are described. Finally, the high growth scenario is described.

# Projection Methods

The SC Office of Revenue and Fiscal Affairs (RFA) publishes population projections for each county in the state. The RFA population projections are stratified by gender and cohort. The projections were developed using the cohort-component method: rates of birth, death, migration are calculated for each gender-cohort in each county; the calculated rates are then applied to the county populations to project future populations year by year. One assumption underlying this method is that the relevant demographic rates calculated from the calibration period will remain uniform across the projection period.

## 2019 Metadata

## 2019 Metadata
The excel file contains the following notes (metadata):

"Population estimates for 2000 and 2018 were calculated using the Bridged-race Intercensal Population Estimates for July 1, 2000 -July 1, 2009 and the Vintage 2018 Bridged-Race Postcensal Estimates for July 1, 2010 -July 1, 2018. These estimates were produced by the Population Estimates Program of the U.S. Census Bureau in collaboration with National Center for Health Statistics. Estimates for 2000 through 2018 from previous or future releases of the postcensal estimates will vary slightly from the 2000 through 2018 data in this table. For all years, the population is estimated for July 1st of that year. Estimates for 2000 and 2010 will not be equivalent to the April 1st decennial census count from Census 2000 and Census 2010."							

"Population Projections for 2019 through 2035 were calculated by the S.C. Revenue and Fiscal Affairs Health and Demographics Section. Births and deaths data used in the population projections calculations was supplied by the SC DHEC Division of Biostatistics.								
							
"Note: The projections included in this report were calculated using the cohort-component model of demographic change. This model uses a base population at a beginning date, applies assumed survival rates, fertility rates, and net migration to calculate population projections.								

"These projections are not intended to be a forecast; rather, they are intended to demonstrate a likely scenario if future events unfold in a manner that reflects previous trends observed within each group. The model cannot account for unprecedented events that may significantly alter an area’s demographic composition in the future. These possible events include large factory openings or closings, changes in technology, public health crises, environmental events, changes in the economy, or other conditions that could affect birth rates, death rates, or domestic and international migration. This means that population projections are likely to be more accurate in the immediate future than in distant years into the future."

## 2022 Metadata

## 2022 Metadata
"Sources: Vintage 2020 Postcensal Estimates for July 1, 2010 -July 1, 2019.  Vintage 2021 Postcensal Estimates for July 1, 2020. These estimates were produced by the Population Estimates Program of the U.S. Census Bureau. Estimates for 2010 through 2020 from previous or future releases of the postcensal estimates will vary slightly from the 2010 through 2020 data in this table. For all years, the population is estimated for July 1st of that year. Estimates for 2020 will not be equivalent to the April 1st decennial census count from Census 2020.

"Population Projections for 2021 through 20230 were calculated by the S.C. Revenue and Fiscal Affairs Data Integration and Analysis Division. Births and deaths data used in the population projections calculations was supplied by the SC DHEC Division of Biostatistics.	

"Note: The projections included in this report were calculated using the cohort-component model of demographic change. This model uses a base population distributed by age and sex at a beginning date, applies assumed survival rates, age-specific fertility rates, and net migration by age and sex to calculate population projections.	

"These projections offer only one possible scenario of future population change using the most current data available. The overall accuracy of the projections depends on the extent to which future events unfold in a manner that reflects previous trends observed within each group. The model cannot account for unprecedented events that may significantly alter an area’s demographic composition in the future. These possible events include large factory openings or closings, changes in technology, public health crises, environmental events, changes in the economy, or other conditions that could affect birth rates, death rates, or domestic and international migration. This means that population projections are likely to be more accurate in the immediate future than in distant years into the future."	

## Growth Scenarios

For the water-demand projections, two scenarios are developed... 